/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  SupportsInterface,
  SupportsInterfaceInterface,
} from "../SupportsInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class SupportsInterface__factory {
  static readonly abi = _abi;
  static createInterface(): SupportsInterfaceInterface {
    return new utils.Interface(_abi) as SupportsInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SupportsInterface {
    return new Contract(address, _abi, signerOrProvider) as SupportsInterface;
  }
}
